"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {store,uid,type JobRecord,type EnquiryRecord,type ApplicationRecord,type WorkerRecord} from "@/lib/store";
type Tab="overview"|"enquiries"|"jobs"|"applications"|"workers"|"settings";
export default function AdminPage(){
 const [tab,setTab]=useState<Tab>("overview"),[jobs,setJobs]=useState<JobRecord[]>([]),[enquiries,setEnquiries]=useState<EnquiryRecord[]>([]),[apps,setApps]=useState<ApplicationRecord[]>([]),[workers,setWorkers]=useState<WorkerRecord[]>([]),[modal,setModal]=useState<"job"|"worker"|null>(null),[search,setSearch]=useState("");
 const load=()=>{setJobs(store.jobs());setEnquiries(store.enquiries());setApps(store.applications());setWorkers(store.workers())};
 useEffect(()=>{load();window.addEventListener("workify-store-change",load);return()=>window.removeEventListener("workify-store-change",load)},[]);
 const q=search.toLowerCase(); const filter=<T,>(arr:T[])=>arr.filter(x=>JSON.stringify(x).toLowerCase().includes(q));
 function saveJob(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);store.saveJobs([{id:uid("j"),role:String(f.get("role")),location:String(f.get("location")),type:String(f.get("type")),vacancies:Number(f.get("vacancies")),deadline:String(f.get("deadline")),status:"Published",summary:String(f.get("summary")),requirements:String(f.get("requirements")).split("\n").filter(Boolean)},...jobs]);setModal(null)}
 function saveWorker(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);store.saveWorkers([{id:uid("w"),name:String(f.get("name")),trade:String(f.get("trade")),county:String(f.get("county")),experience:Number(f.get("experience")),availability:"Available"},...workers]);setModal(null)}
 const nav:[Tab,string][]=[["overview","Overview"],["enquiries","Enquiries"],["jobs","Vacancies"],["applications","Applications"],["workers","Workers"],["settings","Settings"]];
 return <section className="adminLight"><aside className="adminNav"><div className="adminBrand">WORKIFY<span>SOLUTIONS</span></div><nav>{nav.map(([id,label])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{label}<span>{id==="enquiries"?enquiries.length:id==="applications"?apps.length:""}</span></button>)}</nav><a className="adminGallerySidebarLink" href="/admin/projects">Projects</a><a className="adminGallerySidebarLink" href="/admin/gallery">Gallery</a><a href="/" className="backSite">â† Public website</a></aside>
 <main className="adminContent"><header className="adminHeader"><div><span className="eyebrow">CONTROL CENTRE</span><h1>{nav.find(n=>n[0]===tab)?.[1]}</h1></div><div className="adminHeaderActions"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search current records"/>{tab==="jobs"&&<button onClick={()=>setModal("job")}>+ Add vacancy</button>}{tab==="workers"&&<button onClick={()=>setModal("worker")}>+ Add worker</button>}</div></header>
 {tab==="overview"&&<><div className="metricGrid"><Metric n={enquiries.length} l="Client enquiries"/><Metric n={jobs.filter(j=>j.status==="Published").length} l="Published vacancies"/><Metric n={apps.length} l="Applications"/><Metric n={workers.length} l="Registered workers"/></div><div className="overviewGrid"><section className="panel"><PanelTitle t="Recent enquiries"/><EnquiryTable rows={enquiries.slice(0,5)} update={(id,status)=>store.saveEnquiries(enquiries.map(x=>x.id===id?{...x,status}:x))}/></section><section className="panel"><PanelTitle t="Operational snapshot"/><div className="snapshot"><div><strong>{workers.filter(w=>w.availability==="Available").length}</strong><span>Workers available</span></div><div><strong>{apps.filter(a=>a.status==="Shortlisted").length}</strong><span>Shortlisted candidates</span></div></div></section></div></>}
 {tab==="enquiries"&&<section className="panel"><PanelTitle t="All enquiries"/><EnquiryTable rows={filter(enquiries)} update={(id,status)=>store.saveEnquiries(enquiries.map(x=>x.id===id?{...x,status}:x))}/></section>}
 {tab==="jobs"&&<section className="panel"><PanelTitle t="Vacancies"/><table><thead><tr><th>Role</th><th>Location</th><th>Type</th><th>Openings</th><th>Status</th><th></th></tr></thead><tbody>{filter(jobs).length===0&&<tr><td colSpan={6} className="emptyCell">No vacancies have been created.</td></tr>}{filter(jobs).map(j=><tr key={j.id}><td><strong>{j.role}</strong><small>{j.summary}</small></td><td>{j.location}</td><td>{j.type}</td><td>{j.vacancies}</td><td><select value={j.status} onChange={e=>store.saveJobs(jobs.map(x=>x.id===j.id?{...x,status:e.target.value as JobRecord["status"]}:x))}><option>Draft</option><option>Published</option><option>Closed</option></select></td><td><button className="dangerText" onClick={()=>store.saveJobs(jobs.filter(x=>x.id!==j.id))}>Delete</button></td></tr>)}</tbody></table></section>}
 {tab==="applications"&&<section className="panel"><PanelTitle t="Candidate applications"/><table><thead><tr><th>Candidate</th><th>Vacancy</th><th>Experience</th><th>Availability</th><th>Status</th><th>Contact</th></tr></thead><tbody>{filter(apps).length===0&&<tr><td colSpan={6} className="emptyCell">No applications received.</td></tr>}{filter(apps).map(a=><tr key={a.id}><td><strong>{a.name}</strong><small>{a.location}</small></td><td>{a.jobRole}</td><td>{a.experience} years</td><td>{a.availability}</td><td><select value={a.status} onChange={e=>store.saveApplications(apps.map(x=>x.id===a.id?{...x,status:e.target.value as ApplicationRecord["status"]}:x))}><option>Received</option><option>Shortlisted</option><option>Interview</option><option>Selected</option><option>Rejected</option></select></td><td><a href={`mailto:${a.email}`}>{a.email}</a><small>{a.phone}</small></td></tr>)}</tbody></table></section>}
 {tab==="workers"&&<section className="panel"><PanelTitle t="Worker register"/><table><thead><tr><th>Worker</th><th>Trade</th><th>County</th><th>Experience</th><th>Availability</th><th></th></tr></thead><tbody>{filter(workers).length===0&&<tr><td colSpan={6} className="emptyCell">No workers registered.</td></tr>}{filter(workers).map(w=><tr key={w.id}><td><strong>{w.name}</strong></td><td>{w.trade}</td><td>{w.county}</td><td>{w.experience} years</td><td><select value={w.availability} onChange={e=>store.saveWorkers(workers.map(x=>x.id===w.id?{...x,availability:e.target.value as WorkerRecord["availability"]}:x))}><option>Available</option><option>Deployed</option><option>Unavailable</option></select></td><td><button className="dangerText" onClick={()=>store.saveWorkers(workers.filter(x=>x.id!==w.id))}>Delete</button></td></tr>)}</tbody></table></section>}
 {tab==="settings"&&<section className="panel settingsPanel"><PanelTitle t="Application settings"/><p>Operational records shown here reflect submitted or administrator-created data. No sample records are loaded.</p></section>}
 </main>
 {modal&&<div className="modalBackdrop" onMouseDown={()=>setModal(null)}><div className="adminModal" onMouseDown={e=>e.stopPropagation()}><button className="modalClose" onClick={()=>setModal(null)}>Ã—</button>{modal==="job"&&<form onSubmit={saveJob}><h2>Add vacancy</h2><div className="twoCol"><label>Role<input name="role" required/></label><label>Location<input name="location" required/></label></div><div className="twoCol"><label>Type<input name="type" required/></label><label>Vacancies<input name="vacancies" type="number" min="1" required/></label></div><label>Deadline<input name="deadline" required/></label><label>Summary<textarea name="summary" rows={3} required/></label><label>Requirements, one per line<textarea name="requirements" rows={4} required/></label><button type="submit">Publish vacancy</button></form>}{modal==="worker"&&<form onSubmit={saveWorker}><h2>Add worker</h2><label>Name<input name="name" required/></label><div className="twoCol"><label>Trade<input name="trade" required/></label><label>County<input name="county" required/></label></div><label>Experience (years)<input name="experience" type="number" min="0" required/></label><button type="submit">Save worker</button></form>}</div></div>}
 </section>}
function Metric({n,l}:{n:number,l:string}){return <div className="metric"><strong>{n}</strong><span>{l}</span></div>}
function PanelTitle({t}:{t:string}){return <div className="panelTitle"><h2>{t}</h2><span>LIVE DATA</span></div>}
function EnquiryTable({rows,update}:{rows:EnquiryRecord[],update:(id:string,s:EnquiryRecord["status"])=>void}){return <table><thead><tr><th>Client</th><th>Service</th><th>Location</th><th>Date</th><th>Status</th></tr></thead><tbody>{rows.length?rows.map(e=><tr key={e.id}><td><strong>{e.name}</strong><small>{e.organization||e.email}</small></td><td>{e.service}</td><td>{e.location}</td><td>{new Date(e.createdAt).toLocaleDateString()}</td><td><select value={e.status} onChange={x=>update(e.id,x.target.value as EnquiryRecord["status"])}><option>New</option><option>Reviewing</option><option>Quoted</option><option>Closed</option></select></td></tr>):<tr><td colSpan={5} className="emptyCell">No enquiries yet. Submit one through Start a request.</td></tr>}</tbody></table>}



