import Link from "next/link";
export default function Home(){return <>
<section className="minimalHero"><div className="container minimalHeroGrid"><div className="minimalCopy"><span className="eyebrow">PROJECTS + PEOPLE</span><h1>We build projects.<br/>We build teams.</h1><p>Construction delivery, workforce deployment and outsourced recruitment for private clients, companies, NGOs and government institutions.</p><div className="heroActions"><Link href="/construction" className="btn btnPrimary">Start a construction project</Link><Link href="/recruitment" className="btn btnOutline">Request recruitment services</Link></div></div><div className="minimalVisual"><div className="visualHalf lightHalf"><span>01</span><div><small>CONSTRUCTION</small><h2>From plan to handover.</h2></div></div><div className="visualHalf darkHalf"><span>02</span><div><small>RECRUITMENT</small><h2>From requirement to placement.</h2></div></div><aside><span>03</span><strong>02</strong><span>01</span></aside></div></div></section>
<section className="section"><div className="container"><div className="introGrid"><span className="eyebrow">CHOOSE YOUR PATH</span><h2>What do you need today?</h2><p>Each option takes visitors directly to the service and action relevant to them.</p></div><div className="pathGrid">
<Link href="/construction" className="pathCard"><span>01</span><h3>I need a construction partner</h3><p>Complete contracts, renovations, civil works, supervision and delivery.</p><b>Explore construction â†’</b></Link>
<Link href="/workforce" className="pathCard"><span>02</span><h3>I need workers for my site</h3><p>Skilled trades, general labourers, foremen and site supervisors.</p><b>Request workers â†’</b></Link>
<Link href="/recruitment" className="pathCard"><span>03</span><h3>I need staff recruited</h3><p>Sourcing, screening, interviews, verification and reports.</p><b>Outsource recruitment â†’</b></Link>
<Link href="/jobs" className="pathCard"><span>04</span><h3>I am looking for work</h3><p>Browse opportunities and prepare a candidate profile.</p><b>Explore jobs â†’</b></Link>
</div></div></section>
<section className="darkStory"><div className="container storyGrid"><div className="storyNo">02</div><div><span className="eyebrow">TWO DIVISIONS. ONE STANDARD.</span><h2>Infrastructure and people are both essential to delivery.</h2></div><div><p>Some clients need a complete building delivered. Others need people recruited, interviewed or deployed. The website keeps these services distinct while presenting one accountable company.</p><Link href="/about" className="textLink">How we work â†’</Link></div></div></section>
<section className="section"><div className="container ctaBox"><div><span className="eyebrow">START HERE</span><h2>Tell us the outcome you need.</h2></div><Link href="/contact" className="btn btnPrimary">Start a request</Link></div></section>
</>}

