"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import { store,uid,type JobRecord,type ApplicationRecord } from "@/lib/store";

export default function JobsPage(){
 const [jobs,setJobs]=useState<JobRecord[]>([]); const [selectedId,setSelectedId]=useState(""); const [submitted,setSubmitted]=useState(false);
 useEffect(()=>{const load=()=>{const j=store.jobs().filter(x=>x.status==="Published");setJobs(j);setSelectedId(s=>s||j[0]?.id||"")};load();window.addEventListener("workify-store-change",load);return()=>window.removeEventListener("workify-store-change",load)},[]);
 const selected=useMemo(()=>jobs.find(j=>j.id===selectedId)||jobs[0],[jobs,selectedId]);
 function apply(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const fd=new FormData(e.currentTarget);const a:ApplicationRecord={id:uid("app"),jobId:selected.id,jobRole:selected.role,name:String(fd.get("name")),phone:String(fd.get("phone")),email:String(fd.get("email")),location:String(fd.get("location")),experience:Number(fd.get("experience")),availability:String(fd.get("availability")),note:String(fd.get("note")),status:"Received",createdAt:new Date().toISOString()};store.saveApplications([a,...store.applications()]);e.currentTarget.reset();setSubmitted(true)}
 if(!selected)return <section className="section pagePad"><div className="container"><h1>No published vacancies yet.</h1></div></section>;
 return <section className="section pagePad desktopJobsPage"><div className="container">
  <div className="introGrid jobsIntro"><span className="eyebrow">JOB SEEKERS</span><h2>Choose a job and apply beside it.</h2><p>Select a vacancy on the left. Details and the correct form stay visible on the right.</p></div>
  <div className="jobsWorkspace"><div className="jobsMaster"><div className="jobsMasterHead"><span>OPEN VACANCIES</span><strong>{jobs.length}</strong></div><div className="jobSelectList">{jobs.map((job,i)=><button type="button" key={job.id} className={selected.id===job.id?"jobSelectCard active":"jobSelectCard"} onClick={()=>{setSelectedId(job.id);setSubmitted(false)}}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{job.role}</h3><p>{job.location} · {job.type}</p></div><b>{selected.id===job.id?"OPEN":"VIEW"} →</b></button>)}</div></div>
  <aside className="jobSidePanel"><div className="jobPanelTop"><div><span className="eyebrow">SELECTED VACANCY</span><h2>{selected.role}</h2></div><div className="jobReference">{selected.vacancies} OPENING{selected.vacancies!==1?"S":""}</div></div>
   <div className="jobFacts"><div><span>LOCATION</span><strong>{selected.location}</strong></div><div><span>TYPE</span><strong>{selected.type}</strong></div><div><span>VACANCIES</span><strong>{selected.vacancies}</strong></div><div><span>DEADLINE</span><strong>{selected.deadline}</strong></div></div>
   <div className="jobDescription"><h3>About the role</h3><p>{selected.summary}</p><h3>Requirements</h3><ul>{selected.requirements.map(r=><li key={r}>{r}</li>)}</ul></div>
   <form className="inlineJobForm" onSubmit={apply}><div className="inlineFormTitle"><span>APPLY FOR</span><strong>{selected.role}</strong></div><div className="inlineTwoCol"><label>Full name<input name="name" required/></label><label>Phone number<input name="phone" required placeholder="+254..."/></label></div><div className="inlineTwoCol"><label>Email<input name="email" type="email" required/></label><label>Current location<input name="location" required/></label></div><div className="inlineTwoCol"><label>Years of experience<input name="experience" type="number" min="0" required/></label><label>Availability<select name="availability" required defaultValue=""><option value="" disabled>Select</option><option>Immediately</option><option>Within 1 week</option><option>Within 1 month</option></select></label></div><label>Application note<textarea name="note" rows={4} required/></label><div className="inlineTwoCol"><label>CV<input type="file" required accept=".pdf,.doc,.docx"/></label><label>Supporting documents<input type="file" multiple/></label></div><label className="consentLine"><input type="checkbox" required/><span>I confirm the information is accurate.</span></label><button className="btn jobApplyButton" type="submit">Submit application</button>{submitted&&<div className="jobSuccess">Application submitted successfully and is visible in Admin → Applications.</div>}</form>
  </aside></div></div></section>
}
